# Generated by Django 3.2.9 on 2021-12-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Google',
        ),
    ]
